version: "3.8"
services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:

      - PUID=1000
      - PGID=1000
    volumes:
      - ./db_persistance/db:/data/db
    ports:
      - 27017:27017
      - 28017:28017
    restart: unless-stopped
    env_file:
      - ./.env